services:
  backend:
    build:
      context: ./be
      target: development
    container_name: ktx_tb_backend
    ports:
      - "8080:8000"
    volumes:
      - ./be:/app
    env_file:
      - ./be/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/ktx_tb
      JWT_SECRET_KEY: dev-jwt-secret-key
      SECRET_KEY: dev-secret-key
      APP_ENV: development
      DEBUG: "true"
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    restart: unless-stopped
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    container_name: ktx_tb_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ktx_tb
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ktx_tb_mailhog
    restart: unless-stopped
    ports:
      - "1027:1025" # SMTP
      - "8027:8025" # Web UI
    networks:
      - app_network

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      target: development
    container_name: ktx_tb_fe
    restart: unless-stopped
    ports:
      - "5174:5173"
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=
    depends_on:
      - backend
      - mailhog
    networks:
      - app_network
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
