services:
  app:
    build:
      context: .
      target: development
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/ktx_tb
      JWT_SECRET_KEY: dev-jwt-secret-key
      SECRET_KEY: dev-secret-key
      APP_ENV: development
      DEBUG: "true"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ktx_tb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
